spring:
  datasource:
    url: jdbc:postgresql://${event_debug_database.host}:${event_debug_database.port}/${event_debug_database.name}?useUnicode=true&amp;characterEncoding=zh_CN.UTF8&amp;
    username: ${event_debug_database.username}
    password: ${event_debug_database.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      # 从连接池获取连接时最大等待时间, 单位毫秒,   默认值 30秒, 至少 250ms
      connection-timeout: 30000
      # 检测连接是否有效的超时时间，单位毫秒, 默认 5000ms, 最小 250ms, 不能大于connectionTimeout
      validation-timeout: 5000
      # 连接可以在池中的最大闲置时间
      idle-timeout: 600000
      # 连接泄露检测的最大时间, 默认 0, 最低 2000毫秒
      leak-detection-threshold: 0
      # 连接最大存活时间, 单位毫秒, 最小允许值30000 ms, 默认30分钟, 推荐设置的比数据库的 wait_timeout 小几分钟
      max-lifetime: 1800000
      # 连接池中可以保留连接的最大数量
      maximum-pool-size: 100
      # 最小空闲连接数量, 默认 10 个
      minimum-idle: 10