// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bxt.common.math.point.proto

package if_proto_common;

public final class BxtCommonMathPoint {
  private BxtCommonMathPoint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointGPSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:if_proto_common.PointGPS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
     * </pre>
     *
     * <code>optional int32 lat = 1;</code>
     * @return Whether the lat field is set.
     */
    boolean hasLat();
    /**
     * <pre>
     *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
     * </pre>
     *
     * <code>optional int32 lat = 1;</code>
     * @return The lat.
     */
    int getLat();

    /**
     * <pre>
     *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
     * </pre>
     *
     * <code>optional int32 lon = 2;</code>
     * @return Whether the lon field is set.
     */
    boolean hasLon();
    /**
     * <pre>
     *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
     * </pre>
     *
     * <code>optional int32 lon = 2;</code>
     * @return The lon.
     */
    int getLon();

    /**
     * <pre>
     *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
     * </pre>
     *
     * <code>optional int32 ele = 3;</code>
     * @return Whether the ele field is set.
     */
    boolean hasEle();
    /**
     * <pre>
     *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
     * </pre>
     *
     * <code>optional int32 ele = 3;</code>
     * @return The ele.
     */
    int getEle();
  }
  /**
   * Protobuf type {@code if_proto_common.PointGPS}
   */
  public static final class PointGPS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:if_proto_common.PointGPS)
      PointGPSOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PointGPS.newBuilder() to construct.
    private PointGPS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PointGPS() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PointGPS();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PointGPS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              lat_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lon_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ele_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return if_proto_common.BxtCommonMathPoint.internal_static_if_proto_common_PointGPS_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return if_proto_common.BxtCommonMathPoint.internal_static_if_proto_common_PointGPS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              if_proto_common.BxtCommonMathPoint.PointGPS.class, if_proto_common.BxtCommonMathPoint.PointGPS.Builder.class);
    }

    private int bitField0_;
    public static final int LAT_FIELD_NUMBER = 1;
    private int lat_;
    /**
     * <pre>
     *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
     * </pre>
     *
     * <code>optional int32 lat = 1;</code>
     * @return Whether the lat field is set.
     */
    @java.lang.Override
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
     * </pre>
     *
     * <code>optional int32 lat = 1;</code>
     * @return The lat.
     */
    @java.lang.Override
    public int getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 2;
    private int lon_;
    /**
     * <pre>
     *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
     * </pre>
     *
     * <code>optional int32 lon = 2;</code>
     * @return Whether the lon field is set.
     */
    @java.lang.Override
    public boolean hasLon() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
     * </pre>
     *
     * <code>optional int32 lon = 2;</code>
     * @return The lon.
     */
    @java.lang.Override
    public int getLon() {
      return lon_;
    }

    public static final int ELE_FIELD_NUMBER = 3;
    private int ele_;
    /**
     * <pre>
     *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
     * </pre>
     *
     * <code>optional int32 ele = 3;</code>
     * @return Whether the ele field is set.
     */
    @java.lang.Override
    public boolean hasEle() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
     * </pre>
     *
     * <code>optional int32 ele = 3;</code>
     * @return The ele.
     */
    @java.lang.Override
    public int getEle() {
      return ele_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, lat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, lon_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, ele_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lon_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ele_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof if_proto_common.BxtCommonMathPoint.PointGPS)) {
        return super.equals(obj);
      }
      if_proto_common.BxtCommonMathPoint.PointGPS other = (if_proto_common.BxtCommonMathPoint.PointGPS) obj;

      if (hasLat() != other.hasLat()) return false;
      if (hasLat()) {
        if (getLat()
            != other.getLat()) return false;
      }
      if (hasLon() != other.hasLon()) return false;
      if (hasLon()) {
        if (getLon()
            != other.getLon()) return false;
      }
      if (hasEle() != other.hasEle()) return false;
      if (hasEle()) {
        if (getEle()
            != other.getEle()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLat()) {
        hash = (37 * hash) + LAT_FIELD_NUMBER;
        hash = (53 * hash) + getLat();
      }
      if (hasLon()) {
        hash = (37 * hash) + LON_FIELD_NUMBER;
        hash = (53 * hash) + getLon();
      }
      if (hasEle()) {
        hash = (37 * hash) + ELE_FIELD_NUMBER;
        hash = (53 * hash) + getEle();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtCommonMathPoint.PointGPS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(if_proto_common.BxtCommonMathPoint.PointGPS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code if_proto_common.PointGPS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:if_proto_common.PointGPS)
        if_proto_common.BxtCommonMathPoint.PointGPSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return if_proto_common.BxtCommonMathPoint.internal_static_if_proto_common_PointGPS_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return if_proto_common.BxtCommonMathPoint.internal_static_if_proto_common_PointGPS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                if_proto_common.BxtCommonMathPoint.PointGPS.class, if_proto_common.BxtCommonMathPoint.PointGPS.Builder.class);
      }

      // Construct using if_proto_common.BxtCommonMathPoint.PointGPS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ele_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return if_proto_common.BxtCommonMathPoint.internal_static_if_proto_common_PointGPS_descriptor;
      }

      @java.lang.Override
      public if_proto_common.BxtCommonMathPoint.PointGPS getDefaultInstanceForType() {
        return if_proto_common.BxtCommonMathPoint.PointGPS.getDefaultInstance();
      }

      @java.lang.Override
      public if_proto_common.BxtCommonMathPoint.PointGPS build() {
        if_proto_common.BxtCommonMathPoint.PointGPS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public if_proto_common.BxtCommonMathPoint.PointGPS buildPartial() {
        if_proto_common.BxtCommonMathPoint.PointGPS result = new if_proto_common.BxtCommonMathPoint.PointGPS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.lat_ = lat_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lon_ = lon_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ele_ = ele_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof if_proto_common.BxtCommonMathPoint.PointGPS) {
          return mergeFrom((if_proto_common.BxtCommonMathPoint.PointGPS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(if_proto_common.BxtCommonMathPoint.PointGPS other) {
        if (other == if_proto_common.BxtCommonMathPoint.PointGPS.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasEle()) {
          setEle(other.getEle());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if_proto_common.BxtCommonMathPoint.PointGPS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (if_proto_common.BxtCommonMathPoint.PointGPS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int lat_ ;
      /**
       * <pre>
       *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
       * </pre>
       *
       * <code>optional int32 lat = 1;</code>
       * @return Whether the lat field is set.
       */
      @java.lang.Override
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
       * </pre>
       *
       * <code>optional int32 lat = 1;</code>
       * @return The lat.
       */
      @java.lang.Override
      public int getLat() {
        return lat_;
      }
      /**
       * <pre>
       *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
       * </pre>
       *
       * <code>optional int32 lat = 1;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(int value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义纬度数值，北纬为正，南纬为负。分辨率1e-7°，数值900000001 表示未知或无效
       * </pre>
       *
       * <code>optional int32 lat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0;
        onChanged();
        return this;
      }

      private int lon_ ;
      /**
       * <pre>
       *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
       * </pre>
       *
       * <code>optional int32 lon = 2;</code>
       * @return Whether the lon field is set.
       */
      @java.lang.Override
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
       * </pre>
       *
       * <code>optional int32 lon = 2;</code>
       * @return The lon.
       */
      @java.lang.Override
      public int getLon() {
        return lon_;
      }
      /**
       * <pre>
       *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
       * </pre>
       *
       * <code>optional int32 lon = 2;</code>
       * @param value The lon to set.
       * @return This builder for chaining.
       */
      public Builder setLon(int value) {
        bitField0_ |= 0x00000002;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义经度数值。东经为正，西经为负。分辨率为1e-7°， 数值1800000001 为未知或无效。
       * </pre>
       *
       * <code>optional int32 lon = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0;
        onChanged();
        return this;
      }

      private int ele_ ;
      /**
       * <pre>
       *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
       * </pre>
       *
       * <code>optional int32 ele = 3;</code>
       * @return Whether the ele field is set.
       */
      @java.lang.Override
      public boolean hasEle() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
       * </pre>
       *
       * <code>optional int32 ele = 3;</code>
       * @return The ele.
       */
      @java.lang.Override
      public int getEle() {
        return ele_;
      }
      /**
       * <pre>
       *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
       * </pre>
       *
       * <code>optional int32 ele = 3;</code>
       * @param value The ele to set.
       * @return This builder for chaining.
       */
      public Builder setEle(int value) {
        bitField0_ |= 0x00000004;
        ele_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义海拔高程。分辨率为0.1 米，取值范围-4096 到61439，数值-4096 表示无效数值
       * </pre>
       *
       * <code>optional int32 ele = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ele_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:if_proto_common.PointGPS)
    }

    // @@protoc_insertion_point(class_scope:if_proto_common.PointGPS)
    private static final if_proto_common.BxtCommonMathPoint.PointGPS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new if_proto_common.BxtCommonMathPoint.PointGPS();
    }

    public static if_proto_common.BxtCommonMathPoint.PointGPS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PointGPS>
        PARSER = new com.google.protobuf.AbstractParser<PointGPS>() {
      @java.lang.Override
      public PointGPS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PointGPS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PointGPS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointGPS> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public if_proto_common.BxtCommonMathPoint.PointGPS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_if_proto_common_PointGPS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_if_proto_common_PointGPS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033bxt.common.math.point.proto\022\017if_proto_" +
      "common\"1\n\010PointGPS\022\013\n\003lat\030\001 \001(\005\022\013\n\003lon\030\002" +
      " \001(\005\022\013\n\003ele\030\003 \001(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_if_proto_common_PointGPS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_if_proto_common_PointGPS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_if_proto_common_PointGPS_descriptor,
        new java.lang.String[] { "Lat", "Lon", "Ele", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
