// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bxt.StatusPb.proto

package if_proto_common;

public final class BxtStatusPb {
  private BxtStatusPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code if_proto_common.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * No error, reutrns on success.
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <pre>
     * Control module error codes start from here.
     * </pre>
     *
     * <code>CONTROL_ERROR = 1000;</code>
     */
    CONTROL_ERROR(1000),
    /**
     * <code>CONTROL_INIT_ERROR = 1001;</code>
     */
    CONTROL_INIT_ERROR(1001),
    /**
     * <code>CONTROL_COMPUTE_ERROR = 1002;</code>
     */
    CONTROL_COMPUTE_ERROR(1002),
    /**
     * <code>CONTROL_INPUT_ERROR = 1003;</code>
     */
    CONTROL_INPUT_ERROR(1003),
    /**
     * <code>CONTROL_LOCALIZATION_INACCURACY = 1100;</code>
     */
    CONTROL_LOCALIZATION_INACCURACY(1100),
    /**
     * <code>CONTROL_TRAJECTORY_ERROR = 1200;</code>
     */
    CONTROL_TRAJECTORY_ERROR(1200),
    /**
     * <pre>
     * Canbus module error codes start from here.
     * </pre>
     *
     * <code>CANBUS_ERROR = 2000;</code>
     */
    CANBUS_ERROR(2000),
    /**
     * <code>CAN_CLIENT_ERROR_BASE = 2100;</code>
     */
    CAN_CLIENT_ERROR_BASE(2100),
    /**
     * <code>CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED = 2101;</code>
     */
    CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED(2101),
    /**
     * <code>CAN_CLIENT_ERROR_FRAME_NUM = 2102;</code>
     */
    CAN_CLIENT_ERROR_FRAME_NUM(2102),
    /**
     * <code>CAN_CLIENT_ERROR_SEND_FAILED = 2103;</code>
     */
    CAN_CLIENT_ERROR_SEND_FAILED(2103),
    /**
     * <code>CAN_CLIENT_ERROR_RECV_FAILED = 2104;</code>
     */
    CAN_CLIENT_ERROR_RECV_FAILED(2104),
    /**
     * <pre>
     * Localization module error codes start from here.
     * </pre>
     *
     * <code>LOCALIZATION_ERROR = 3000;</code>
     */
    LOCALIZATION_ERROR(3000),
    /**
     * <code>LOCALIZATION_ERROR_MSG = 3100;</code>
     */
    LOCALIZATION_ERROR_MSG(3100),
    /**
     * <code>LOCALIZATION_ERROR_LIDAR = 3200;</code>
     */
    LOCALIZATION_ERROR_LIDAR(3200),
    /**
     * <code>LOCALIZATION_ERROR_INTEG = 3300;</code>
     */
    LOCALIZATION_ERROR_INTEG(3300),
    /**
     * <code>LOCALIZATION_ERROR_GNSS = 3400;</code>
     */
    LOCALIZATION_ERROR_GNSS(3400),
    /**
     * <pre>
     * Perception module error codes start from here.
     * </pre>
     *
     * <code>PERCEPTION_ERROR = 4000;</code>
     */
    PERCEPTION_ERROR(4000),
    /**
     * <code>PERCEPTION_ERROR_TF = 4001;</code>
     */
    PERCEPTION_ERROR_TF(4001),
    /**
     * <code>PERCEPTION_ERROR_PROCESS = 4002;</code>
     */
    PERCEPTION_ERROR_PROCESS(4002),
    /**
     * <code>PERCEPTION_FATAL = 4003;</code>
     */
    PERCEPTION_FATAL(4003),
    /**
     * <pre>
     * Prediction module error codes start from here.
     * </pre>
     *
     * <code>PREDICTION_ERROR = 5000;</code>
     */
    PREDICTION_ERROR(5000),
    /**
     * <pre>
     * HDMap module error codes start from here.
     * </pre>
     *
     * <code>HDMAP_ERROR = 6000;</code>
     */
    HDMAP_ERROR(6000),
    /**
     * <code>HDMAP_PARAMS_ERROR = 6001;</code>
     */
    HDMAP_PARAMS_ERROR(6001),
    /**
     * <pre>
     * Planning module error codes start from here.
     * </pre>
     *
     * <code>PLANNING_ERROR = 7000;</code>
     */
    PLANNING_ERROR(7000),
    /**
     * <pre>
     * Routing module error codes
     * </pre>
     *
     * <code>ROUTING_ERROR = 8000;</code>
     */
    ROUTING_ERROR(8000),
    /**
     * <code>ROUTING_ERROR_REQUEST = 8001;</code>
     */
    ROUTING_ERROR_REQUEST(8001),
    /**
     * <code>ROUTING_ERROR_RESPONSE = 8002;</code>
     */
    ROUTING_ERROR_RESPONSE(8002),
    /**
     * <code>ROUTING_ERROR_NOT_READY = 8003;</code>
     */
    ROUTING_ERROR_NOT_READY(8003),
    /**
     * <pre>
     * Indicates an input has been exhausted.
     * </pre>
     *
     * <code>END_OF_INPUT = 9000;</code>
     */
    END_OF_INPUT(9000),
    /**
     * <pre>
     * HTTP request error codes.
     * </pre>
     *
     * <code>HTTP_LOGIC_ERROR = 10000;</code>
     */
    HTTP_LOGIC_ERROR(10000),
    /**
     * <code>HTTP_RUNTIME_ERROR = 10001;</code>
     */
    HTTP_RUNTIME_ERROR(10001),
    /**
     * <pre>
     * Drivers error codes.
     * </pre>
     *
     * <code>DRIVERS_ERROR = 11000;</code>
     */
    DRIVERS_ERROR(11000),
    /**
     * <code>DRIVERS_RADAR_ERROR = 11001;</code>
     */
    DRIVERS_RADAR_ERROR(11001),
    /**
     * <code>DRIVERS_LIDAR_ERROR = 11002;</code>
     */
    DRIVERS_LIDAR_ERROR(11002),
    /**
     * <code>DRIVERS_CAMERA_ERROR = 11003;</code>
     */
    DRIVERS_CAMERA_ERROR(11003),
    /**
     * <code>DRIVERS_GPS_ERROR = 11004;</code>
     */
    DRIVERS_GPS_ERROR(11004),
    /**
     * <pre>
     * Simulation module error codes
     * </pre>
     *
     * <code>SIMULATION_GRPC_ERROR = 12001;</code>
     */
    SIMULATION_GRPC_ERROR(12001),
    /**
     * <code>SIMULATION_ERROR = 12002;</code>
     */
    SIMULATION_ERROR(12002),
    /**
     * <pre>
     * integration_test error codes.
     * </pre>
     *
     * <code>INTEGRATION_TEST_CONFIG_XML_ERROR = 13000;</code>
     */
    INTEGRATION_TEST_CONFIG_XML_ERROR(13000),
    /**
     * <code>INTEGRATION_TEST_DUMP_LABEL_DATA_ERROR = 13001;</code>
     */
    INTEGRATION_TEST_DUMP_LABEL_DATA_ERROR(13001),
    /**
     * <pre>
     * calibration error codes.
     * </pre>
     *
     * <code>CALIBRATION_ERROR = 14000;</code>
     */
    CALIBRATION_ERROR(14000),
    ;

    /**
     * <pre>
     * No error, reutrns on success.
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * Control module error codes start from here.
     * </pre>
     *
     * <code>CONTROL_ERROR = 1000;</code>
     */
    public static final int CONTROL_ERROR_VALUE = 1000;
    /**
     * <code>CONTROL_INIT_ERROR = 1001;</code>
     */
    public static final int CONTROL_INIT_ERROR_VALUE = 1001;
    /**
     * <code>CONTROL_COMPUTE_ERROR = 1002;</code>
     */
    public static final int CONTROL_COMPUTE_ERROR_VALUE = 1002;
    /**
     * <code>CONTROL_INPUT_ERROR = 1003;</code>
     */
    public static final int CONTROL_INPUT_ERROR_VALUE = 1003;
    /**
     * <code>CONTROL_LOCALIZATION_INACCURACY = 1100;</code>
     */
    public static final int CONTROL_LOCALIZATION_INACCURACY_VALUE = 1100;
    /**
     * <code>CONTROL_TRAJECTORY_ERROR = 1200;</code>
     */
    public static final int CONTROL_TRAJECTORY_ERROR_VALUE = 1200;
    /**
     * <pre>
     * Canbus module error codes start from here.
     * </pre>
     *
     * <code>CANBUS_ERROR = 2000;</code>
     */
    public static final int CANBUS_ERROR_VALUE = 2000;
    /**
     * <code>CAN_CLIENT_ERROR_BASE = 2100;</code>
     */
    public static final int CAN_CLIENT_ERROR_BASE_VALUE = 2100;
    /**
     * <code>CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED = 2101;</code>
     */
    public static final int CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED_VALUE = 2101;
    /**
     * <code>CAN_CLIENT_ERROR_FRAME_NUM = 2102;</code>
     */
    public static final int CAN_CLIENT_ERROR_FRAME_NUM_VALUE = 2102;
    /**
     * <code>CAN_CLIENT_ERROR_SEND_FAILED = 2103;</code>
     */
    public static final int CAN_CLIENT_ERROR_SEND_FAILED_VALUE = 2103;
    /**
     * <code>CAN_CLIENT_ERROR_RECV_FAILED = 2104;</code>
     */
    public static final int CAN_CLIENT_ERROR_RECV_FAILED_VALUE = 2104;
    /**
     * <pre>
     * Localization module error codes start from here.
     * </pre>
     *
     * <code>LOCALIZATION_ERROR = 3000;</code>
     */
    public static final int LOCALIZATION_ERROR_VALUE = 3000;
    /**
     * <code>LOCALIZATION_ERROR_MSG = 3100;</code>
     */
    public static final int LOCALIZATION_ERROR_MSG_VALUE = 3100;
    /**
     * <code>LOCALIZATION_ERROR_LIDAR = 3200;</code>
     */
    public static final int LOCALIZATION_ERROR_LIDAR_VALUE = 3200;
    /**
     * <code>LOCALIZATION_ERROR_INTEG = 3300;</code>
     */
    public static final int LOCALIZATION_ERROR_INTEG_VALUE = 3300;
    /**
     * <code>LOCALIZATION_ERROR_GNSS = 3400;</code>
     */
    public static final int LOCALIZATION_ERROR_GNSS_VALUE = 3400;
    /**
     * <pre>
     * Perception module error codes start from here.
     * </pre>
     *
     * <code>PERCEPTION_ERROR = 4000;</code>
     */
    public static final int PERCEPTION_ERROR_VALUE = 4000;
    /**
     * <code>PERCEPTION_ERROR_TF = 4001;</code>
     */
    public static final int PERCEPTION_ERROR_TF_VALUE = 4001;
    /**
     * <code>PERCEPTION_ERROR_PROCESS = 4002;</code>
     */
    public static final int PERCEPTION_ERROR_PROCESS_VALUE = 4002;
    /**
     * <code>PERCEPTION_FATAL = 4003;</code>
     */
    public static final int PERCEPTION_FATAL_VALUE = 4003;
    /**
     * <pre>
     * Prediction module error codes start from here.
     * </pre>
     *
     * <code>PREDICTION_ERROR = 5000;</code>
     */
    public static final int PREDICTION_ERROR_VALUE = 5000;
    /**
     * <pre>
     * HDMap module error codes start from here.
     * </pre>
     *
     * <code>HDMAP_ERROR = 6000;</code>
     */
    public static final int HDMAP_ERROR_VALUE = 6000;
    /**
     * <code>HDMAP_PARAMS_ERROR = 6001;</code>
     */
    public static final int HDMAP_PARAMS_ERROR_VALUE = 6001;
    /**
     * <pre>
     * Planning module error codes start from here.
     * </pre>
     *
     * <code>PLANNING_ERROR = 7000;</code>
     */
    public static final int PLANNING_ERROR_VALUE = 7000;
    /**
     * <pre>
     * Routing module error codes
     * </pre>
     *
     * <code>ROUTING_ERROR = 8000;</code>
     */
    public static final int ROUTING_ERROR_VALUE = 8000;
    /**
     * <code>ROUTING_ERROR_REQUEST = 8001;</code>
     */
    public static final int ROUTING_ERROR_REQUEST_VALUE = 8001;
    /**
     * <code>ROUTING_ERROR_RESPONSE = 8002;</code>
     */
    public static final int ROUTING_ERROR_RESPONSE_VALUE = 8002;
    /**
     * <code>ROUTING_ERROR_NOT_READY = 8003;</code>
     */
    public static final int ROUTING_ERROR_NOT_READY_VALUE = 8003;
    /**
     * <pre>
     * Indicates an input has been exhausted.
     * </pre>
     *
     * <code>END_OF_INPUT = 9000;</code>
     */
    public static final int END_OF_INPUT_VALUE = 9000;
    /**
     * <pre>
     * HTTP request error codes.
     * </pre>
     *
     * <code>HTTP_LOGIC_ERROR = 10000;</code>
     */
    public static final int HTTP_LOGIC_ERROR_VALUE = 10000;
    /**
     * <code>HTTP_RUNTIME_ERROR = 10001;</code>
     */
    public static final int HTTP_RUNTIME_ERROR_VALUE = 10001;
    /**
     * <pre>
     * Drivers error codes.
     * </pre>
     *
     * <code>DRIVERS_ERROR = 11000;</code>
     */
    public static final int DRIVERS_ERROR_VALUE = 11000;
    /**
     * <code>DRIVERS_RADAR_ERROR = 11001;</code>
     */
    public static final int DRIVERS_RADAR_ERROR_VALUE = 11001;
    /**
     * <code>DRIVERS_LIDAR_ERROR = 11002;</code>
     */
    public static final int DRIVERS_LIDAR_ERROR_VALUE = 11002;
    /**
     * <code>DRIVERS_CAMERA_ERROR = 11003;</code>
     */
    public static final int DRIVERS_CAMERA_ERROR_VALUE = 11003;
    /**
     * <code>DRIVERS_GPS_ERROR = 11004;</code>
     */
    public static final int DRIVERS_GPS_ERROR_VALUE = 11004;
    /**
     * <pre>
     * Simulation module error codes
     * </pre>
     *
     * <code>SIMULATION_GRPC_ERROR = 12001;</code>
     */
    public static final int SIMULATION_GRPC_ERROR_VALUE = 12001;
    /**
     * <code>SIMULATION_ERROR = 12002;</code>
     */
    public static final int SIMULATION_ERROR_VALUE = 12002;
    /**
     * <pre>
     * integration_test error codes.
     * </pre>
     *
     * <code>INTEGRATION_TEST_CONFIG_XML_ERROR = 13000;</code>
     */
    public static final int INTEGRATION_TEST_CONFIG_XML_ERROR_VALUE = 13000;
    /**
     * <code>INTEGRATION_TEST_DUMP_LABEL_DATA_ERROR = 13001;</code>
     */
    public static final int INTEGRATION_TEST_DUMP_LABEL_DATA_ERROR_VALUE = 13001;
    /**
     * <pre>
     * calibration error codes.
     * </pre>
     *
     * <code>CALIBRATION_ERROR = 14000;</code>
     */
    public static final int CALIBRATION_ERROR_VALUE = 14000;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1000: return CONTROL_ERROR;
        case 1001: return CONTROL_INIT_ERROR;
        case 1002: return CONTROL_COMPUTE_ERROR;
        case 1003: return CONTROL_INPUT_ERROR;
        case 1100: return CONTROL_LOCALIZATION_INACCURACY;
        case 1200: return CONTROL_TRAJECTORY_ERROR;
        case 2000: return CANBUS_ERROR;
        case 2100: return CAN_CLIENT_ERROR_BASE;
        case 2101: return CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED;
        case 2102: return CAN_CLIENT_ERROR_FRAME_NUM;
        case 2103: return CAN_CLIENT_ERROR_SEND_FAILED;
        case 2104: return CAN_CLIENT_ERROR_RECV_FAILED;
        case 3000: return LOCALIZATION_ERROR;
        case 3100: return LOCALIZATION_ERROR_MSG;
        case 3200: return LOCALIZATION_ERROR_LIDAR;
        case 3300: return LOCALIZATION_ERROR_INTEG;
        case 3400: return LOCALIZATION_ERROR_GNSS;
        case 4000: return PERCEPTION_ERROR;
        case 4001: return PERCEPTION_ERROR_TF;
        case 4002: return PERCEPTION_ERROR_PROCESS;
        case 4003: return PERCEPTION_FATAL;
        case 5000: return PREDICTION_ERROR;
        case 6000: return HDMAP_ERROR;
        case 6001: return HDMAP_PARAMS_ERROR;
        case 7000: return PLANNING_ERROR;
        case 8000: return ROUTING_ERROR;
        case 8001: return ROUTING_ERROR_REQUEST;
        case 8002: return ROUTING_ERROR_RESPONSE;
        case 8003: return ROUTING_ERROR_NOT_READY;
        case 9000: return END_OF_INPUT;
        case 10000: return HTTP_LOGIC_ERROR;
        case 10001: return HTTP_RUNTIME_ERROR;
        case 11000: return DRIVERS_ERROR;
        case 11001: return DRIVERS_RADAR_ERROR;
        case 11002: return DRIVERS_LIDAR_ERROR;
        case 11003: return DRIVERS_CAMERA_ERROR;
        case 11004: return DRIVERS_GPS_ERROR;
        case 12001: return SIMULATION_GRPC_ERROR;
        case 12002: return SIMULATION_ERROR;
        case 13000: return INTEGRATION_TEST_CONFIG_XML_ERROR;
        case 13001: return INTEGRATION_TEST_DUMP_LABEL_DATA_ERROR;
        case 14000: return CALIBRATION_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return if_proto_common.BxtStatusPb.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:if_proto_common.ErrorCode)
  }

  public interface StatusPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:if_proto_common.StatusPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
     * @return Whether the errorCode field is set.
     */
    boolean hasErrorCode();
    /**
     * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
     * @return The errorCode.
     */
    if_proto_common.BxtStatusPb.ErrorCode getErrorCode();

    /**
     * <code>optional string msg = 2;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code if_proto_common.StatusPb}
   */
  public static final class StatusPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:if_proto_common.StatusPb)
      StatusPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StatusPb.newBuilder() to construct.
    private StatusPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatusPb() {
      errorCode_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StatusPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StatusPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              if_proto_common.BxtStatusPb.ErrorCode value = if_proto_common.BxtStatusPb.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errorCode_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return if_proto_common.BxtStatusPb.internal_static_if_proto_common_StatusPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return if_proto_common.BxtStatusPb.internal_static_if_proto_common_StatusPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              if_proto_common.BxtStatusPb.StatusPb.class, if_proto_common.BxtStatusPb.StatusPb.Builder.class);
    }

    private int bitField0_;
    public static final int ERROR_CODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
     * @return Whether the errorCode field is set.
     */
    @java.lang.Override public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
     * @return The errorCode.
     */
    @java.lang.Override public if_proto_common.BxtStatusPb.ErrorCode getErrorCode() {
      @SuppressWarnings("deprecation")
      if_proto_common.BxtStatusPb.ErrorCode result = if_proto_common.BxtStatusPb.ErrorCode.valueOf(errorCode_);
      return result == null ? if_proto_common.BxtStatusPb.ErrorCode.OK : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof if_proto_common.BxtStatusPb.StatusPb)) {
        return super.equals(obj);
      }
      if_proto_common.BxtStatusPb.StatusPb other = (if_proto_common.BxtStatusPb.StatusPb) obj;

      if (hasErrorCode() != other.hasErrorCode()) return false;
      if (hasErrorCode()) {
        if (errorCode_ != other.errorCode_) return false;
      }
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrorCode()) {
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + errorCode_;
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static if_proto_common.BxtStatusPb.StatusPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(if_proto_common.BxtStatusPb.StatusPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code if_proto_common.StatusPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:if_proto_common.StatusPb)
        if_proto_common.BxtStatusPb.StatusPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return if_proto_common.BxtStatusPb.internal_static_if_proto_common_StatusPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return if_proto_common.BxtStatusPb.internal_static_if_proto_common_StatusPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                if_proto_common.BxtStatusPb.StatusPb.class, if_proto_common.BxtStatusPb.StatusPb.Builder.class);
      }

      // Construct using if_proto_common.BxtStatusPb.StatusPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return if_proto_common.BxtStatusPb.internal_static_if_proto_common_StatusPb_descriptor;
      }

      @java.lang.Override
      public if_proto_common.BxtStatusPb.StatusPb getDefaultInstanceForType() {
        return if_proto_common.BxtStatusPb.StatusPb.getDefaultInstance();
      }

      @java.lang.Override
      public if_proto_common.BxtStatusPb.StatusPb build() {
        if_proto_common.BxtStatusPb.StatusPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public if_proto_common.BxtStatusPb.StatusPb buildPartial() {
        if_proto_common.BxtStatusPb.StatusPb result = new if_proto_common.BxtStatusPb.StatusPb(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof if_proto_common.BxtStatusPb.StatusPb) {
          return mergeFrom((if_proto_common.BxtStatusPb.StatusPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(if_proto_common.BxtStatusPb.StatusPb other) {
        if (other == if_proto_common.BxtStatusPb.StatusPb.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if_proto_common.BxtStatusPb.StatusPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (if_proto_common.BxtStatusPb.StatusPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ = 0;
      /**
       * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
       * @return Whether the errorCode field is set.
       */
      @java.lang.Override public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
       * @return The errorCode.
       */
      @java.lang.Override
      public if_proto_common.BxtStatusPb.ErrorCode getErrorCode() {
        @SuppressWarnings("deprecation")
        if_proto_common.BxtStatusPb.ErrorCode result = if_proto_common.BxtStatusPb.ErrorCode.valueOf(errorCode_);
        return result == null ? if_proto_common.BxtStatusPb.ErrorCode.OK : result;
      }
      /**
       * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(if_proto_common.BxtStatusPb.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .if_proto_common.ErrorCode error_code = 1 [default = OK];</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:if_proto_common.StatusPb)
    }

    // @@protoc_insertion_point(class_scope:if_proto_common.StatusPb)
    private static final if_proto_common.BxtStatusPb.StatusPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new if_proto_common.BxtStatusPb.StatusPb();
    }

    public static if_proto_common.BxtStatusPb.StatusPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StatusPb>
        PARSER = new com.google.protobuf.AbstractParser<StatusPb>() {
      @java.lang.Override
      public StatusPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatusPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StatusPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatusPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public if_proto_common.BxtStatusPb.StatusPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_if_proto_common_StatusPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_if_proto_common_StatusPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022bxt.StatusPb.proto\022\017if_proto_common\"K\n" +
      "\010StatusPb\0222\n\nerror_code\030\001 \001(\0162\032.if_proto" +
      "_common.ErrorCode:\002OK\022\013\n\003msg\030\002 \001(\t*\224\t\n\tE" +
      "rrorCode\022\006\n\002OK\020\000\022\022\n\rCONTROL_ERROR\020\350\007\022\027\n\022" +
      "CONTROL_INIT_ERROR\020\351\007\022\032\n\025CONTROL_COMPUTE" +
      "_ERROR\020\352\007\022\030\n\023CONTROL_INPUT_ERROR\020\353\007\022$\n\037C" +
      "ONTROL_LOCALIZATION_INACCURACY\020\314\010\022\035\n\030CON" +
      "TROL_TRAJECTORY_ERROR\020\260\t\022\021\n\014CANBUS_ERROR" +
      "\020\320\017\022\032\n\025CAN_CLIENT_ERROR_BASE\020\264\020\022(\n#CAN_C" +
      "LIENT_ERROR_OPEN_DEVICE_FAILED\020\265\020\022\037\n\032CAN" +
      "_CLIENT_ERROR_FRAME_NUM\020\266\020\022!\n\034CAN_CLIENT" +
      "_ERROR_SEND_FAILED\020\267\020\022!\n\034CAN_CLIENT_ERRO" +
      "R_RECV_FAILED\020\270\020\022\027\n\022LOCALIZATION_ERROR\020\270" +
      "\027\022\033\n\026LOCALIZATION_ERROR_MSG\020\234\030\022\035\n\030LOCALI" +
      "ZATION_ERROR_LIDAR\020\200\031\022\035\n\030LOCALIZATION_ER" +
      "ROR_INTEG\020\344\031\022\034\n\027LOCALIZATION_ERROR_GNSS\020" +
      "\310\032\022\025\n\020PERCEPTION_ERROR\020\240\037\022\030\n\023PERCEPTION_" +
      "ERROR_TF\020\241\037\022\035\n\030PERCEPTION_ERROR_PROCESS\020" +
      "\242\037\022\025\n\020PERCEPTION_FATAL\020\243\037\022\025\n\020PREDICTION_" +
      "ERROR\020\210\'\022\020\n\013HDMAP_ERROR\020\360.\022\027\n\022HDMAP_PARA" +
      "MS_ERROR\020\361.\022\023\n\016PLANNING_ERROR\020\3306\022\022\n\rROUT" +
      "ING_ERROR\020\300>\022\032\n\025ROUTING_ERROR_REQUEST\020\301>" +
      "\022\033\n\026ROUTING_ERROR_RESPONSE\020\302>\022\034\n\027ROUTING" +
      "_ERROR_NOT_READY\020\303>\022\021\n\014END_OF_INPUT\020\250F\022\025" +
      "\n\020HTTP_LOGIC_ERROR\020\220N\022\027\n\022HTTP_RUNTIME_ER" +
      "ROR\020\221N\022\022\n\rDRIVERS_ERROR\020\370U\022\030\n\023DRIVERS_RA" +
      "DAR_ERROR\020\371U\022\030\n\023DRIVERS_LIDAR_ERROR\020\372U\022\031" +
      "\n\024DRIVERS_CAMERA_ERROR\020\373U\022\026\n\021DRIVERS_GPS" +
      "_ERROR\020\374U\022\032\n\025SIMULATION_GRPC_ERROR\020\341]\022\025\n" +
      "\020SIMULATION_ERROR\020\342]\022&\n!INTEGRATION_TEST" +
      "_CONFIG_XML_ERROR\020\310e\022+\n&INTEGRATION_TEST" +
      "_DUMP_LABEL_DATA_ERROR\020\311e\022\026\n\021CALIBRATION" +
      "_ERROR\020\260m"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_if_proto_common_StatusPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_if_proto_common_StatusPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_if_proto_common_StatusPb_descriptor,
        new java.lang.String[] { "ErrorCode", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
